//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CongNghePhanMemTienTien.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonViThucTap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonViThucTap()
        {
            this.DVTTQuanLies = new HashSet<DVTTQuanLy>();
            this.SinhVienThucTaps = new HashSet<SinhVienThucTap>();
        }
    
        public int ID { get; set; }
        public string TenDonVi { get; set; }
        public string Link { get; set; }
        public string Website { get; set; }
        public string Email { get; set; }
        public string SoDienThoai { get; set; }
        public string DaiDien { get; set; }
        public string Fax { get; set; }
        public string DaiChi { get; set; }
        public string Logo { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> CreatedUser { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<int> DeletedUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DVTTQuanLy> DVTTQuanLies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SinhVienThucTap> SinhVienThucTaps { get; set; }
    }
}
