//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CongNghePhanMemTienTien.DataContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CNPMTTEntities : DbContext
    {
        public CNPMTTEntities()
            : base("name=CNPMTTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietDiemDanh> ChiTietDiemDanhs { get; set; }
        public virtual DbSet<DiemDanhSV> DiemDanhSVs { get; set; }
        public virtual DbSet<DonViThucTap> DonViThucTaps { get; set; }
        public virtual DbSet<DVTTQuanLy> DVTTQuanLies { get; set; }
        public virtual DbSet<GiangVien> GiangViens { get; set; }
        public virtual DbSet<Khoa> Khoas { get; set; }
        public virtual DbSet<Lop> Lops { get; set; }
        public virtual DbSet<PhuHuynh> PhuHuynhs { get; set; }
        public virtual DbSet<SinhVien> SinhViens { get; set; }
        public virtual DbSet<SinhVienThucTap> SinhVienThucTaps { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<ChuyenNganh> ChuyenNganhs { get; set; }
        public virtual DbSet<Nganh> Nganhs { get; set; }
        public virtual DbSet<DanhMucThongBao> DanhMucThongBaos { get; set; }
        public virtual DbSet<GIangVien_MonHoc> GIangVien_MonHoc { get; set; }
        public virtual DbSet<Gv_Khoa> Gv_Khoa { get; set; }
        public virtual DbSet<Gv_Khoa_Detail> Gv_Khoa_Detail { get; set; }
        public virtual DbSet<Sv_Gv_Detail> Sv_Gv_Detail { get; set; }
        public virtual DbSet<Sv_Khoa_Detail> Sv_Khoa_Detail { get; set; }
        public virtual DbSet<Ca> Cas { get; set; }
        public virtual DbSet<MonHoc> MonHocs { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<RoleDetail> RoleDetails { get; set; }
        public virtual DbSet<UserAdmin> UserAdmins { get; set; }
    }
}
